# Generated by Django 5.2.1 on 2025-06-19 18:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='turno',
            field=models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
