# Generated by Django 5.2.1 on 2025-06-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_turno_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='turno',
            field=models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde')], default='M', max_length=1),
        ),
    ]
