# Generated by Django 5.2.1 on 2025-06-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_venta_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaitem',
            name='producto',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='total',
            new_name='total_a_cobrar',
        ),
        migrations.RenameField(
            model_name='ventaitem',
            old_name='precio_unitario',
            new_name='precio',
        ),
        migrations.AddField(
            model_name='venta',
            name='total_cobrado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='codigo_hacedor',
            field=models.CharField(default='X', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='codigo_producto',
            field=models.CharField(default='Y', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='nombre',
            field=models.CharField(default='Z', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
