# Generated by Django 5.2.1 on 2025-06-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_remove_ventaitem_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cuenta_transferencia',
            field=models.CharField(blank=True, choices=[('Vale', 'Vale'), ('Dani', 'Dani'), ('Vero', 'Vero')], null=True),
        ),
        migrations.AlterField(
            model_name='ventaitem',
            name='codigo_hacedor',
            field=models.CharField(choices=[('IL', 'Ilanto'), ('AC', 'Aguaclara'), ('DS', 'Desopeton')]),
        ),
    ]
