# Generated by Django 5.2.1 on 2025-06-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_ventaitem_codigo_hacedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaitem',
            name='codigo_producto',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
