# Generated by Django 5.2.1 on 2025-06-27 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_alter_ventaitem_codigo_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventaitem',
            old_name='nombre',
            new_name='producto',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cuenta_transferencia',
        ),
        migrations.RemoveField(
            model_name='ventaitem',
            name='codigo_hacedor',
        ),
    ]
