# Generated by Django 5.2.1 on 2025-06-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_rename_nombre_ventaitem_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cuenta_transferencia',
            field=models.CharField(default='agus_admin'),
            preserve_default=False,
        ),
    ]
