# Generated by Django 5.2.1 on 2025-06-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_alter_venta_cuenta_transferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cuenta_transferencia',
            field=models.CharField(),
        ),
    ]
