# Generated by Django 5.2.1 on 2025-06-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_alter_venta_cuenta_transferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaitem',
            name='codigo_emprendimiento',
            field=models.CharField(default='EX2', max_length=4),
            preserve_default=False,
        ),
    ]
