# Generated by Django 5.2.1 on 2025-05-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='interno',
            field=models.BooleanField(default=False, verbose_name='¿Pertenece a la cooperativa?'),
        ),
    ]
